const DAYS=['Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi','Dimanche'];
const COLORS={green:'#16855b',gray:'#9ba7ad',blue:'#2563eb',origin:'#0d4863'};
const PAGE_SIZE=10;
let appData=null,map=null,markers=new Map(),originMarker=null,userOrigin=null,deferredPrompt=null,currentPage=0;
const $=s=>document.querySelector(s);
function mins(t){if(!t||!/^[0-2]\d:[0-5]\d$/.test(t))return NaN;const [h,m]=t.split(':').map(Number);return h*60+m}
function hav(a,b,c,d){if(![a,b,c,d].every(Number.isFinite))return null;const R=6371,rad=x=>x*Math.PI/180,p1=rad(a),p2=rad(c),dp=rad(c-a),dl=rad(d-b);const q=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function formatDist(km){if(!Number.isFinite(km))return 'Distance n/d';return km<1?`${Math.round(km*1000)} m`:`${km.toFixed(1).replace('.',',')} km`}
function todayFr(){const js=(new Date().getDay()+6)%7;return DAYS[js]}
function nowHHMM(){const d=new Date(),m=Math.floor(d.getMinutes()/15)*15;return `${String(d.getHours()).padStart(2,'0')}:${String(m).padStart(2,'0')}`}
function isLane(cat=''){return /(couloir|longueur|corridor)/i.test(cat)}
function isEligibleCategory(cat=''){return /(adulte|nage en|couloir|longueur|corridor|toutes et tous|pour tous|12\+)/i.test(cat)&&!/(aîné|ainé|enfant|famille|familial|trans|fille|femme|pataugeoire)/i.test(cat)}
function matchingSlots(pool,day,time,laneOnly){if(pool.scheduleStatus!=='live')return [];const m=mins(time);if(!Number.isFinite(m))return [];let xs=(pool.slots||[]).filter(s=>isEligibleCategory(s.category)&&s.day===day&&mins(s.start)<=m&&m<=mins(s.end));if(laneOnly){const lane=xs.filter(s=>isLane(s.category));if(lane.length)return lane}return xs}
function nextSlot(pool,day,time){if(pool.scheduleStatus!=='live')return null;const m=mins(time);return (pool.slots||[]).filter(s=>isEligibleCategory(s.category)&&s.day===day&&mins(s.start)>m).sort((a,b)=>mins(a.start)-mins(b.start))[0]||null}
function mapsUrl(pool){const dest=encodeURIComponent(pool.address);const origin=userOrigin?`&origin=${userOrigin.lat},${userOrigin.lon}`:'';return `https://www.google.com/maps/dir/?api=1${origin}&destination=${dest}&travelmode=walking`}
function sourceUrl(pool){return pool.source||appData.officialIndoorDirectory}
function icon(color,recommended=false){if(!window.L)return null;const size=recommended?22:16;return L.divIcon({className:'custom-marker',html:`<div style="width:${size}px;height:${size}px;border-radius:50%;background:${color};border:3px solid white;box-shadow:0 1px 7px rgba(0,0,0,.35)"></div>`,iconSize:[size,size],iconAnchor:[size/2,size/2]})}
function hasCoords(p){return Number.isFinite(p.lat)&&Number.isFinite(p.lon)}
function setOrigin(origin,label){userOrigin=origin;currentPage=0;$('#locationStatus').textContent=`Point de départ : ${label}`;if(map&&window.L){if(originMarker)map.removeLayer(originMarker);originMarker=L.circleMarker([origin.lat,origin.lon],{radius:7,color:'#fff',weight:2,fillColor:COLORS.origin,fillOpacity:1}).addTo(map).bindTooltip(label);map.setView([origin.lat,origin.lon],13)}render()}
function poolState(){const day=$('#daySelect').value,time=$('#timeInput').value,laneOnly=$('#lanePriority').checked;const fallback=appData.mapCenter;const origin=userOrigin||fallback;const all=appData.pools.map(p=>{const match=matchingSlots(p,day,time,laneOnly)[0]||null;const distance=hasCoords(p)?hav(origin.lat,origin.lon,p.lat,p.lon):null;return {...p,available:!!match,match,distance,next:nextSlot(p,day,time)}});
 const sortDistance=(a,b)=>{if(Number.isFinite(a.distance)&&Number.isFinite(b.distance))return a.distance-b.distance;if(Number.isFinite(a.distance))return -1;if(Number.isFinite(b.distance))return 1;return a.name.localeCompare(b.name,'fr')};
 all.sort(sortDistance);
 const available=all.filter(p=>p.available).sort((a,b)=>{const laneDiff=(isLane(b.match?.category)?1:0)-(isLane(a.match?.category)?1:0);return laneDiff||sortDistance(a,b)});
 return {all,available,recommended:available[0]||null,day,time,hasOrigin:!!userOrigin}}
function statusText(p,state){if(p.available)return `${p.match.category} · ${p.match.start}–${p.match.end}`;if(p.scheduleStatus==='closed')return p.status||'Fermée temporairement';if(p.scheduleStatus==='future')return p.status||'Ouverture à venir';if(p.scheduleStatus==='seasonal')return p.status||'Hors saison';if(p.scheduleStatus==='external')return 'Horaire à consulter sur la source officielle';if(p.next)return `Prochain : ${p.next.category} · ${p.next.start}–${p.next.end}`;return 'Pas de créneau plus tard aujourd’hui'}
function renderRec(state){const box=$('#recommendation'),p=state.recommended;if(!p){box.className='recommendation empty';box.innerHTML=`<div><div class="rec-title"><h2>Aucune piscine avec horaire intégré disponible à ${state.time}</h2></div><p class="rec-meta">Essaie une autre heure. Certaines piscines gratuites ont un horaire externe : leur fiche reste disponible dans la liste.</p></div>`;return}const proximity=state.hasOrigin?`${formatDist(p.distance)} · `:'Choisis un départ pour affiner la proximité · ';box.className='recommendation';box.innerHTML=`<div><div class="rec-title"><span class="pill">🏆 Recommandée</span><h2>${p.name}</h2></div><p class="rec-meta"><strong>${p.match.category}</strong> · ${p.match.start}–${p.match.end} · ${proximity}${p.address}</p></div><div class="rec-actions"><a class="primary rec-route" href="${mapsUrl(p)}" target="_blank" rel="noopener">Itinéraire</a><a class="secondary" href="${sourceUrl(p)}" target="_blank" rel="noopener">Horaire officiel</a></div>`}
function renderList(state){const totalPages=Math.max(1,Math.ceil(state.all.length/PAGE_SIZE));currentPage=Math.min(currentPage,totalPages-1);const start=currentPage*PAGE_SIZE,page=state.all.slice(start,start+PAGE_SIZE);$('#countBadge').textContent=`${state.available.length} disponible${state.available.length>1?'s':''} · ${state.all.length} recensées`;const positioned=state.all.filter(hasCoords).length;$('#mapSummary').textContent=`${state.day} à ${state.time} · ${state.available.length} disponible${state.available.length>1?'s':''} · ${positioned}/${state.all.length} positionnées sur la carte`;$('#listNote').textContent=state.hasOrigin?'Classées par distance depuis ton point de départ. 10 piscines par page.':'Choisis un point de départ pour classer précisément par distance. 10 piscines par page.';$('#poolList').innerHTML=page.map(p=>{const rec=state.recommended&&p.name===state.recommended.name;const dist=state.hasOrigin?formatDist(p.distance):(hasCoords(p)?'—':'Position n/d');return `<article class="pool-row ${rec?'recommended-row':''}"><span class="availability ${rec?'recommended':p.available?'on':'off'}"></span><div><div class="pool-name">${rec?'🏆 ':''}${p.name}</div><div class="pool-sub">${p.arrondissement} · ${p.type||''}</div></div><div class="slot">${statusText(p,state)}</div><div class="distance">${dist}</div><div class="row-actions"><a href="${mapsUrl(p)}" target="_blank" rel="noopener">Y aller</a><a href="${sourceUrl(p)}" target="_blank" rel="noopener">Source</a></div></article>`}).join('');$('#pageInfo').textContent=`${start+1}–${Math.min(start+PAGE_SIZE,state.all.length)} sur ${state.all.length} · page ${currentPage+1}/${totalPages}`;$('#prevPage').disabled=currentPage===0;$('#nextPage').disabled=currentPage>=totalPages-1}
function renderMap(state){if(!map||!window.L)return;const activeNames=new Set();for(const p of state.all){if(!hasCoords(p))continue;activeNames.add(p.name);const rec=state.recommended&&p.name===state.recommended.name,color=rec?COLORS.blue:(p.available?COLORS.green:COLORS.gray);let m=markers.get(p.name);if(!m){m=L.marker([p.lat,p.lon],{icon:icon(color,rec)}).addTo(map);markers.set(p.name,m)}else{m.setLatLng([p.lat,p.lon]);m.setIcon(icon(color,rec))}const dist=userOrigin?`${formatDist(p.distance)} depuis ton point de départ`:'Choisis un point de départ pour calculer la distance';m.bindPopup(`<div class="popup"><h3>${p.name}</h3><p>${statusText(p,state)}</p><p>${dist}</p><p>${p.address}</p><a href="${mapsUrl(p)}" target="_blank" rel="noopener">Ouvrir l’itinéraire →</a></div>`)}for(const [name,m] of markers){if(!activeNames.has(name)){map.removeLayer(m);markers.delete(name)}}}
function render(){if(!appData)return;const state=poolState();renderRec(state);renderList(state);renderMap(state)}
function populateTimes(){const sel=$('#timeQuickSelect');sel.innerHTML='<option value="">Liste 15 min</option>';for(let m=0;m<24*60;m+=15){const h=String(Math.floor(m/60)).padStart(2,'0'),mm=String(m%60).padStart(2,'0'),v=`${h}:${mm}`;const o=document.createElement('option');o.value=v;o.textContent=v;sel.append(o)}}
function syncQuickFromInput(){const v=$('#timeInput').value;$('#timeQuickSelect').value=[...$('#timeQuickSelect').options].some(o=>o.value===v)?v:''}
function initMap(){if(!window.L){$('#map').classList.add('hidden');$('#mapFallback').classList.remove('hidden');return}map=L.map('map',{zoomControl:true}).setView([appData.mapCenter.lat,appData.mapCenter.lon],11.4);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);const pts=appData.pools.filter(hasCoords).map(p=>L.latLng(p.lat,p.lon));if(pts.length>1)map.fitBounds(L.latLngBounds(pts).pad(.08))}
async function geocodeAddress(raw){const q=raw.trim();if(q.length<4)throw new Error('Adresse trop courte');const params=new URLSearchParams({format:'jsonv2',limit:'1',countrycodes:'ca','accept-language':'fr',q:`${q}, Montréal, Québec`});const url=`https://nominatim.openstreetmap.org/search?${params}`;const res=await fetch(url,{headers:{Accept:'application/json'}});if(!res.ok)throw new Error('Service de géocodage indisponible');const arr=await res.json();if(!arr.length)throw new Error('Adresse introuvable');const hit=arr[0];return {origin:{lat:Number(hit.lat),lon:Number(hit.lon)},label:hit.display_name.split(',').slice(0,3).join(',')}}
async function init(){const res=await fetch('./data.json',{cache:'no-store'});appData=await res.json();for(const d of DAYS){const op=document.createElement('option');op.value=d;op.textContent=d;$('#daySelect').append(op)}populateTimes();$('#daySelect').value=todayFr();$('#timeInput').value=nowHHMM();syncQuickFromInput();$('#updated').textContent=`Mise à jour des données : ${appData.updated} · ${appData.pools.length} installations recensées.`;initMap();['daySelect','lanePriority'].forEach(id=>$('#'+id).addEventListener('change',()=>{currentPage=0;render()}));$('#timeInput').addEventListener('input',()=>{syncQuickFromInput();currentPage=0;render()});$('#timeQuickSelect').addEventListener('change',e=>{if(e.target.value){$('#timeInput').value=e.target.value;currentPage=0;render()}});$('#locateBtn').addEventListener('click',()=>{if(!navigator.geolocation){$('#locationStatus').textContent='Géolocalisation non disponible sur cet appareil.';return}$('#locationStatus').textContent='Recherche de ta position…';navigator.geolocation.getCurrentPosition(pos=>setOrigin({lat:pos.coords.latitude,lon:pos.coords.longitude},'Ma position'),()=>{$('#locationStatus').textContent='Position non autorisée ou indisponible. Tu peux entrer une adresse.'},{enableHighAccuracy:true,timeout:10000,maximumAge:60000})});$('#addressForm').addEventListener('submit',async e=>{e.preventDefault();const input=$('#addressInput'),btn=$('#addressBtn'),old=btn.textContent;btn.disabled=true;btn.textContent='Recherche…';$('#locationStatus').textContent='Recherche de l’adresse…';try{const r=await geocodeAddress(input.value);setOrigin(r.origin,r.label)}catch(err){$('#locationStatus').textContent=err.message||'Adresse introuvable.'}finally{btn.disabled=false;btn.textContent=old}});$('#prevPage').addEventListener('click',()=>{if(currentPage>0){currentPage--;render();document.querySelector('.list-card').scrollIntoView({behavior:'smooth',block:'start'})}});$('#nextPage').addEventListener('click',()=>{const max=Math.ceil(appData.pools.length/PAGE_SIZE)-1;if(currentPage<max){currentPage++;render();document.querySelector('.list-card').scrollIntoView({behavior:'smooth',block:'start'})}});render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').classList.add('hidden')}else if(/iphone|ipad|ipod/i.test(navigator.userAgent)){$('#iosHelp').showModal()}});if(/iphone|ipad|ipod/i.test(navigator.userAgent)&&!window.matchMedia('(display-mode: standalone)').matches){$('#installBtn').classList.remove('hidden')}init().catch(err=>{console.error(err);document.body.insertAdjacentHTML('beforeend','<p style="padding:20px">Impossible de charger les données de l’application.</p>')});