const DAYS=['Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi','Dimanche'];
const COLORS={green:'#16855b',gray:'#9ba7ad',orange:'#df7a22',origin:'#0d4863'};
const adultCategories=['Adultes 16+','Adultes','Nage en couloir 16+','Nage en couloir','Toutes et tous'];
let appData=null,map=null,markers=new Map(),originMarker=null,userOrigin=null,deferredPrompt=null;
const $=s=>document.querySelector(s);
function mins(t){const [h,m]=t.split(':').map(Number);return h*60+m}
function hav(a,b,c,d){const R=6371,rad=x=>x*Math.PI/180,p1=rad(a),p2=rad(c),dp=rad(c-a),dl=rad(d-b);const q=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function formatDist(km){return km<1?`${Math.round(km*1000)} m`:`${km.toFixed(1).replace('.',',')} km`}
function todayFr(){const js=(new Date().getDay()+6)%7;return DAYS[js]}
function nowHHMM(){const d=new Date();return `${String(d.getHours()).padStart(2,'0')}:${String(Math.floor(d.getMinutes()/5)*5).padStart(2,'0')}`}
function isLane(cat){return /couloir/i.test(cat)}
function matchingSlots(pool,day,time,laneOnly){const m=mins(time);let slots=pool.slots.filter(s=>adultCategories.includes(s.category)&&s.day===day&&mins(s.start)<=m&&m<=mins(s.end));if(laneOnly){const lane=slots.filter(s=>isLane(s.category));if(lane.length) return lane}return slots}
function nextSlot(pool,day,time){const m=mins(time);return pool.slots.filter(s=>adultCategories.includes(s.category)&&s.day===day&&mins(s.start)>m).sort((a,b)=>mins(a.start)-mins(b.start))[0]||null}
function mapsUrl(pool){const o=userOrigin?`${userOrigin.lat},${userOrigin.lon}`:encodeURIComponent(appData.referenceOrigin.address);const d=encodeURIComponent(pool.address);return `https://www.google.com/maps/dir/?api=1&origin=${o}&destination=${d}&travelmode=walking`}
function sourceUrl(pool){return pool.source}
function icon(color,recommended=false){if(!window.L)return null;return L.divIcon({className:'custom-marker',html:`<div style="width:${recommended?22:16}px;height:${recommended?22:16}px;border-radius:50%;background:${color};border:3px solid white;box-shadow:0 1px 7px rgba(0,0,0,.35)"></div>`,iconSize:[recommended?22:16,recommended?22:16],iconAnchor:[recommended?11:8,recommended?11:8]})}
function setOrigin(origin,label){userOrigin=origin;$('#locationStatus').textContent=`Point de départ : ${label}`;if(map&&window.L){if(originMarker)map.removeLayer(originMarker);originMarker=L.circleMarker([origin.lat,origin.lon],{radius:7,color:'#fff',weight:2,fillColor:COLORS.origin,fillOpacity:1}).addTo(map).bindTooltip(label);map.panTo([origin.lat,origin.lon])}render()}
function poolState(){const day=$('#daySelect').value,time=$('#timeInput').value,laneOnly=$('#lanePriority').checked;const origin=userOrigin||appData.referenceOrigin;const all=appData.pools.map(p=>{const slots=matchingSlots(p,day,time,laneOnly);const distance=hav(origin.lat,origin.lon,p.lat,p.lon);return {...p,available:slots.length>0,match:slots[0]||null,distance,next:nextSlot(p,day,time)}});const available=all.filter(p=>p.available).sort((a,b)=>{const laneDiff=(isLane(b.match?.category||'')?1:0)-(isLane(a.match?.category||'')?1:0);return laneDiff||a.distance-b.distance});const recommended=available[0]||null;return {all:all.sort((a,b)=>a.distance-b.distance),available,recommended,day,time}}
function renderRec(state){const box=$('#recommendation');const p=state.recommended;if(!p){box.className='recommendation empty';box.innerHTML=`<div><div class="rec-title"><h2>Aucune piscine disponible à ${state.time}</h2></div><p class="rec-meta">Essaie une autre heure. La liste indique aussi les prochains créneaux du jour.</p></div>`;return}box.className='recommendation';box.innerHTML=`<div><div class="rec-title"><span class="pill">🏆 Recommandée</span><h2>${p.name}</h2></div><p class="rec-meta"><strong>${p.match.category}</strong> · ${p.match.start}–${p.match.end} · ${formatDist(p.distance)} · ${p.address}</p></div><div class="rec-actions"><a class="primary" style="text-decoration:none" href="${mapsUrl(p)}" target="_blank" rel="noopener">Itinéraire</a><a class="secondary" style="text-decoration:none" href="${sourceUrl(p)}" target="_blank" rel="noopener">Horaire officiel</a></div>`}
function renderList(state){$('#countBadge').textContent=`${state.available.length} disponible${state.available.length>1?'s':''}`;$('#mapSummary').textContent=`${state.day} à ${state.time} · ${state.available.length} piscine${state.available.length>1?'s':''} disponible${state.available.length>1?'s':''}`;$('#poolList').innerHTML=state.all.map(p=>{const rec=state.recommended&&p.name===state.recommended.name;const slot=p.available?`${p.match.category} · ${p.match.start}–${p.match.end}`:(p.next?`Prochain : ${p.next.category} · ${p.next.start}–${p.next.end}`:'Pas de créneau plus tard aujourd’hui');return `<article class="pool-row ${rec?'recommended-row':''}"><span class="availability ${p.available?'on':'off'}"></span><div><div class="pool-name">${rec?'🏆 ':''}${p.name}</div><div class="pool-sub">${p.arrondissement}</div></div><div class="slot">${slot}</div><div class="distance">${formatDist(p.distance)}</div><div class="row-actions"><a href="${mapsUrl(p)}" target="_blank" rel="noopener">Y aller</a><a href="${p.source}" target="_blank" rel="noopener">Source</a></div></article>`}).join('')}
function renderMap(state){if(!map||!window.L)return;for(const p of state.all){const rec=state.recommended&&p.name===state.recommended.name;const color=rec?COLORS.orange:(p.available?COLORS.green:COLORS.gray);let m=markers.get(p.name);if(!m){m=L.marker([p.lat,p.lon],{icon:icon(color,rec)}).addTo(map);markers.set(p.name,m)}else m.setIcon(icon(color,rec));const slot=p.available?`${p.match.category}<br>${p.match.start}–${p.match.end}`:'Indisponible à cette heure';m.bindPopup(`<div class="popup"><h3>${p.name}</h3><p>${slot}</p><p>${formatDist(p.distance)} depuis ton point de départ</p><p>${p.address}</p><a href="${mapsUrl(p)}" target="_blank" rel="noopener">Ouvrir l’itinéraire →</a></div>`)} }
function render(){if(!appData)return;const state=poolState();renderRec(state);renderList(state);renderMap(state)}
function initMap(){if(!window.L){$('#map').classList.add('hidden');$('#mapFallback').classList.remove('hidden');return}map=L.map('map',{zoomControl:true}).setView([45.535,-73.58],12.5);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);const o=appData.referenceOrigin;originMarker=L.circleMarker([o.lat,o.lon],{radius:7,color:'#fff',weight:2,fillColor:COLORS.origin,fillOpacity:1}).addTo(map).bindTooltip(o.name);const group=L.featureGroup(appData.pools.map(p=>L.marker([p.lat,p.lon])));map.fitBounds(group.getBounds().pad(.18));}
async function init(){const res=await fetch('./data.json');appData=await res.json();for(const d of DAYS){const op=document.createElement('option');op.value=d;op.textContent=d;$('#daySelect').append(op)}$('#daySelect').value=todayFr();$('#timeInput').value=nowHHMM();$('#updated').textContent=`Mise à jour des données : ${appData.updated}.`;initMap();setOrigin(appData.referenceOrigin,appData.referenceOrigin.name);['daySelect','timeInput','lanePriority'].forEach(id=>$('#'+id).addEventListener('change',render));$('#locateBtn').addEventListener('click',()=>{if(!navigator.geolocation){$('#locationStatus').textContent='Géolocalisation non disponible sur cet appareil.';return}$('#locationStatus').textContent='Recherche de ta position…';navigator.geolocation.getCurrentPosition(pos=>setOrigin({lat:pos.coords.latitude,lon:pos.coords.longitude},'Ma position'),err=>{$('#locationStatus').textContent='Position non autorisée ou indisponible. Le métro Mont-Royal reste la référence.'},{enableHighAccuracy:true,timeout:10000,maximumAge:60000})});$('#metroBtn').addEventListener('click',()=>setOrigin(appData.referenceOrigin,appData.referenceOrigin.name));render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').classList.add('hidden')}else if(/iphone|ipad|ipod/i.test(navigator.userAgent)){$('#iosHelp').showModal()}});if(/iphone|ipad|ipod/i.test(navigator.userAgent)&&!window.matchMedia('(display-mode: standalone)').matches){$('#installBtn').classList.remove('hidden')}init().catch(err=>{console.error(err);document.body.insertAdjacentHTML('beforeend','<p style="padding:20px">Impossible de charger les données de l’application.</p>')});
